# alias
alias vi="vim -X"
alias tmux="tmux -2"
alias wc="wc -l"
alias top="htop"
alias ls="lsd"
alias cat="bat -pp"
alias less="bat --wrap never"
alias grep="rg -N"
alias find="fd"
alias mkdir="mkdir -p"
alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -i"
alias ln="ln -i"
